SERVER_APP_NAME = 'test'
SERVER_APP_SOCKET_PATH = '/var/opt/test/mysock.sock'
SERVER_APP_SOCKET_PORT = ''
SERVER_APP_DOMAIN = '127.0.0.1'
SERVER_APP_MEDIA_FOLDER = '/var/opt/test/media/'
SERVER_APP_STATIC_FOLDER = SERVER_APP_MEDIA_FOLDER = '/var/opt/test/statics/'
SERVER_APP_WSGI_PARAMS_PATH = '/var/opt/test/nginx/uwsgi_params'
SERVER_APP_BASE_FOLDER = '/var/opt/test/test/'
SERVER_APP_SYSTEM_USER = 'www-data'
SERVER_APP_VENV_PATH = '/var/opt/test/env'
